# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0002_auto_20170718_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2017-07-19'),
        ),
    ]
